server:
  port: 9090

spring:
  freemarker:
    prefer-file-system-access: false
  application:
       name: jjzuul
  profiles:
#      active: local
      active: dev
#      active: prod
#eureka:
#  client:
#    service-url:
#       defaultZone: http://106.15.47.133:10000/eureka/

#配置路由
zuul:
  routes:
     jjgroupclass: /jjgroupclass/**
     jjuserbase: /jjuserbase/**
     jjsport: /jjsport/**
     jjdiet: /jjdiet/**


# spring boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
