server:
  port: 9090

spring:
  freemarker:
    prefer-file-system-access: false
  application:
       name: jjzuul

eureka:
  client:
    service-url:
       defaultZone: http://192.168.0.201:8888/eureka/

#配置路由
zuul:
  routes:
        #路由地址
        #要转发的服务名称
     server-a:
        path: /ehomeuser/**
        serviceId: EhomeUser
# spring boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
