server:
  port: 9090

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: jjzuul
  profiles:
    active: dev

#配置路由
zuul:
  routes:
     jjgroupclass: /jjgroupclass/**



# spring boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
